CREATE DATABASE adocaoanimal DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE adocaoanimal;

CREATE TABLE animal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  peso FLOAT NOT NULL,
  sexo VARCHAR(10) NOT NULL,
  descricao TEXT NOT NULL,
  historico TEXT NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  status_animal VARCHAR(50) NOT NULL
)DEFAULT CHARSET = utf8;